import type { Task, Project, Group, GroupMember, UserProfile, ChatMessage, Notification } from './types';

// ── Demo user ────────────────────────────────────────────────
export const DEMO_USER_PROFILE: UserProfile = {
  uid: 'demo-user-001',
  email: 'demo@taskzenith.app',
  displayName: 'Usuario Demo',
  role: 'admin',
};

// ── Projects ─────────────────────────────────────────────────
export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-website',
    name: 'Rediseño Website',
    color: '#3b82f6',
    description: 'Rediseño completo del sitio web corporativo',
    createdBy: 'demo-user-001',
  },
  {
    id: 'proj-app',
    name: 'App Móvil',
    color: '#10b981',
    description: 'Desarrollo de la aplicación móvil para clientes',
    createdBy: 'demo-user-001',
  },
  {
    id: 'proj-marketing',
    name: 'Campaña Q1',
    color: '#f59e0b',
    description: 'Campaña de marketing primer trimestre 2026',
    createdBy: 'demo-user-001',
  },
  {
    id: 'proj-infra',
    name: 'Infraestructura',
    color: '#8b5cf6',
    description: 'Mejoras de infraestructura y DevOps',
    createdBy: 'demo-user-001',
  },
];

// ── Tasks ────────────────────────────────────────────────────
const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000);
const daysFromNow = (d: number) => new Date(now.getTime() + d * 86400000);

export const DEMO_TASKS: Task[] = [
  // ── Website project tasks
  {
    id: 'task-001',
    title: 'Diseñar mockups nueva landing page',
    category: 'design',
    priority: 'alta',
    completed: false,
    createdAt: daysAgo(5),
    startedAt: daysAgo(3),
    dueDate: daysFromNow(2),
    projectId: 'proj-website',
    status: 'En Progreso',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-001',
    subTasks: [
      { id: 'sub-001-1', title: 'Wireframes desktop', completed: true },
      { id: 'sub-001-2', title: 'Wireframes mobile', completed: true },
      { id: 'sub-001-3', title: 'Mockup alta fidelidad', completed: false },
    ],
    timeSpent: 7200,
    estimatedTime: 180,
  },
  {
    id: 'task-002',
    title: 'Implementar sistema de autenticación OAuth',
    category: 'development',
    priority: 'alta',
    completed: false,
    createdAt: daysAgo(7),
    startedAt: daysAgo(2),
    dueDate: daysFromNow(5),
    projectId: 'proj-website',
    status: 'En Progreso',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-002',
    subTasks: [
      { id: 'sub-002-1', title: 'Configurar proveedores OAuth', completed: true },
      { id: 'sub-002-2', title: 'Backend endpoints', completed: false },
      { id: 'sub-002-3', title: 'Frontend login flow', completed: false },
    ],
    timeSpent: 3600,
    estimatedTime: 240,
  },
  {
    id: 'task-003',
    title: 'Optimizar rendimiento de carga (Core Web Vitals)',
    category: 'development',
    priority: 'media',
    completed: false,
    createdAt: daysAgo(3),
    dueDate: daysFromNow(7),
    projectId: 'proj-website',
    status: 'Pendiente',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-001',
    estimatedTime: 120,
  },
  {
    id: 'task-004',
    title: 'Migrar base de datos a PostgreSQL',
    category: 'development',
    priority: 'alta',
    completed: true,
    createdAt: daysAgo(15),
    startedAt: daysAgo(12),
    completedAt: daysAgo(2),
    projectId: 'proj-website',
    status: 'Finalizado',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-001',
    timeSpent: 14400,
    estimatedTime: 300,
  },

  // ── App project tasks
  {
    id: 'task-005',
    title: 'Configurar proyecto React Native',
    category: 'development',
    priority: 'alta',
    completed: true,
    createdAt: daysAgo(20),
    startedAt: daysAgo(19),
    completedAt: daysAgo(17),
    projectId: 'proj-app',
    status: 'Finalizado',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-002',
    timeSpent: 5400,
    estimatedTime: 120,
  },
  {
    id: 'task-006',
    title: 'Diseñar UI/UX del onboarding',
    category: 'design',
    priority: 'media',
    completed: false,
    createdAt: daysAgo(4),
    startedAt: daysAgo(1),
    dueDate: daysFromNow(4),
    projectId: 'proj-app',
    status: 'En Progreso',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-001',
    subTasks: [
      { id: 'sub-006-1', title: 'Investigación de usuario', completed: true },
      { id: 'sub-006-2', title: 'Flujo de pantallas', completed: false },
      { id: 'sub-006-3', title: 'Prototipos interactivos', completed: false },
    ],
    estimatedTime: 240,
    timeSpent: 1800,
  },
  {
    id: 'task-007',
    title: 'Integrar push notifications',
    category: 'development',
    priority: 'media',
    completed: false,
    createdAt: daysAgo(2),
    dueDate: daysFromNow(10),
    projectId: 'proj-app',
    status: 'Pendiente',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-002',
    estimatedTime: 180,
  },

  // ── Marketing project tasks
  {
    id: 'task-008',
    title: 'Crear contenido para redes sociales (Febrero)',
    category: 'marketing',
    priority: 'media',
    completed: true,
    createdAt: daysAgo(25),
    startedAt: daysAgo(22),
    completedAt: daysAgo(5),
    projectId: 'proj-marketing',
    status: 'Finalizado',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-003',
    timeSpent: 10800,
    estimatedTime: 300,
  },
  {
    id: 'task-009',
    title: 'Diseñar newsletter mensual',
    category: 'marketing',
    priority: 'baja',
    completed: false,
    createdAt: daysAgo(3),
    dueDate: daysFromNow(1),
    projectId: 'proj-marketing',
    status: 'Pendiente',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-003',
    estimatedTime: 60,
  },
  {
    id: 'task-010',
    title: 'Analizar métricas de conversión Q4',
    category: 'marketing',
    priority: 'alta',
    completed: false,
    createdAt: daysAgo(1),
    dueDate: daysFromNow(3),
    projectId: 'proj-marketing',
    status: 'En Progreso',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-001',
    startedAt: daysAgo(1),
    timeSpent: 900,
    estimatedTime: 120,
  },

  // ── Infra tasks
  {
    id: 'task-011',
    title: 'Configurar pipeline CI/CD',
    category: 'development',
    priority: 'alta',
    completed: true,
    createdAt: daysAgo(30),
    startedAt: daysAgo(28),
    completedAt: daysAgo(20),
    projectId: 'proj-infra',
    status: 'Finalizado',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-002',
    timeSpent: 18000,
    estimatedTime: 360,
  },
  {
    id: 'task-012',
    title: 'Implementar monitoreo con alertas',
    category: 'development',
    priority: 'media',
    completed: false,
    createdAt: daysAgo(6),
    dueDate: daysFromNow(8),
    projectId: 'proj-infra',
    status: 'Pendiente',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-001',
    estimatedTime: 240,
  },

  // ── Tasks sin proyecto
  {
    id: 'task-013',
    title: 'Revisar documentación de API',
    category: 'development',
    priority: 'baja',
    completed: false,
    createdAt: daysAgo(1),
    dueDate: daysFromNow(5),
    status: 'Pendiente',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-001',
    estimatedTime: 60,
  },
  {
    id: 'task-014',
    title: 'Reunión de planificación sprint',
    category: 'management',
    priority: 'alta',
    completed: false,
    createdAt: daysAgo(0),
    dueDate: daysFromNow(0),
    status: 'Pendiente',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-001',
    estimatedTime: 30,
  },
  {
    id: 'task-015',
    title: 'Actualizar dependencias del proyecto',
    category: 'development',
    priority: 'baja',
    completed: false,
    createdAt: daysAgo(2),
    status: 'Pendiente',
    createdBy: 'demo-user-001',
    assignedTo: 'demo-user-002',
    estimatedTime: 45,
  },
];

// ── Groups ───────────────────────────────────────────────────
export const DEMO_GROUPS: Group[] = [
  {
    id: 'group-dev',
    name: 'Equipo Desarrollo',
    description: 'Equipo principal de desarrollo de software',
    color: '#3b82f6',
    createdBy: 'demo-user-001',
    createdAt: daysAgo(60).getTime(),
    inviteCode: 'DEV2026A',
  },
  {
    id: 'group-mkt',
    name: 'Marketing Digital',
    description: 'Equipo de marketing y comunicaciones',
    color: '#f59e0b',
    createdBy: 'demo-user-001',
    createdAt: daysAgo(45).getTime(),
    inviteCode: 'MKT2026B',
  },
];

export const DEMO_GROUP_MEMBERS: Record<string, GroupMember[]> = {
  'group-dev': [
    {
      id: 'demo-user-001',
      uid: 'demo-user-001',
      displayName: 'Usuario Demo',
      email: 'demo@taskzenith.app',
      role: 'admin',
      memberFunction: 'administración',
      joinedAt: daysAgo(60).getTime(),
    },
    {
      id: 'demo-user-002',
      uid: 'demo-user-002',
      displayName: 'Carlos López',
      email: 'carlos@empresa.com',
      role: 'operator',
      memberFunction: 'desarrollo',
      joinedAt: daysAgo(55).getTime(),
    },
    {
      id: 'demo-user-004',
      uid: 'demo-user-004',
      displayName: 'Ana Martínez',
      email: 'ana@empresa.com',
      role: 'operator',
      memberFunction: 'diseño',
      joinedAt: daysAgo(50).getTime(),
    },
  ],
  'group-mkt': [
    {
      id: 'demo-user-001',
      uid: 'demo-user-001',
      displayName: 'Usuario Demo',
      email: 'demo@taskzenith.app',
      role: 'admin',
      memberFunction: 'administración',
      joinedAt: daysAgo(45).getTime(),
    },
    {
      id: 'demo-user-003',
      uid: 'demo-user-003',
      displayName: 'María García',
      email: 'maria@empresa.com',
      role: 'operator',
      memberFunction: 'marketing',
      joinedAt: daysAgo(40).getTime(),
    },
  ],
};

// ── Chat messages ────────────────────────────────────────────
export const DEMO_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-001',
    senderId: 'demo-user-002',
    senderName: 'Carlos López',
    content: '¡Buenos días equipo! Ya terminé la migración de la base de datos 🎉',
    channelId: 'general',
    createdAt: daysAgo(2).getTime(),
  },
  {
    id: 'msg-002',
    senderId: 'demo-user-001',
    senderName: 'Usuario Demo',
    content: '¡Excelente Carlos! ¿Pudiste verificar que todos los datos migraron correctamente?',
    channelId: 'general',
    createdAt: daysAgo(2).getTime() + 60000,
  },
  {
    id: 'msg-003',
    senderId: 'demo-user-002',
    senderName: 'Carlos López',
    content: 'Sí, corrí todas las validaciones y todo está en orden. Los tests pasan al 100%.',
    channelId: 'general',
    createdAt: daysAgo(2).getTime() + 120000,
  },
  {
    id: 'msg-004',
    senderId: 'demo-user-003',
    senderName: 'María García',
    content: 'Hola, ya tengo listos los contenidos para redes sociales de esta semana 📱',
    channelId: 'marketing',
    createdAt: daysAgo(1).getTime(),
  },
  {
    id: 'msg-005',
    senderId: 'demo-user-004',
    senderName: 'Ana Martínez',
    content: 'Subí los nuevos mockups al proyecto. ¿Alguien puede revisarlos?',
    channelId: 'development',
    createdAt: daysAgo(0).getTime(),
  },
];

// ── Notifications ────────────────────────────────────────────
export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    userId: 'demo-user-001',
    type: 'task_completed',
    title: 'Tarea completada',
    message: 'Carlos completó "Migrar base de datos a PostgreSQL"',
    read: false,
    createdAt: daysAgo(2).getTime(),
  },
  {
    id: 'notif-002',
    userId: 'demo-user-001',
    type: 'message',
    title: 'Nuevo mensaje en #general',
    message: 'Carlos López envió un mensaje',
    read: false,
    createdAt: daysAgo(2).getTime() + 60000,
  },
  {
    id: 'notif-003',
    userId: 'demo-user-001',
    type: 'task_assigned',
    title: 'Nueva tarea asignada',
    message: 'Se te asignó "Reunión de planificación sprint"',
    read: true,
    createdAt: daysAgo(0).getTime(),
  },
];

// ── Tour steps ───────────────────────────────────────────────
export interface TourStep {
  target: string; // CSS selector or data attribute
  title: string;
  description: string;
  placement: 'top' | 'bottom' | 'left' | 'right' | 'center';
  page?: string; // Route to navigate to for this step
}

export const DEMO_TOUR_STEPS: TourStep[] = [
  {
    target: '[data-tour="dashboard"]',
    title: '¡Bienvenido a TaskZenith! 🚀',
    description: 'Este es tu dashboard personalizable. Aquí puedes ver un resumen completo de tu actividad: estadísticas, tareas pendientes, calendario y más. Los widgets se pueden mover y redimensionar.',
    placement: 'center',
    page: '/dashboard',
  },
  {
    target: '[data-tour="stats"]',
    title: 'Estadísticas en tiempo real 📊',
    description: 'Estas tarjetas muestran un resumen rápido: tareas totales, completadas, en progreso y vencidas. Se actualizan automáticamente.',
    placement: 'bottom',
    page: '/dashboard',
  },
  {
    target: '[data-tour="todo-list"]',
    title: 'Lista de tareas ✅',
    description: 'Gestiona tus tareas desde aquí. Puedes crear, editar, asignar prioridades, fechas de vencimiento y agruparlas por proyecto. Haz clic en una tarea para ver todos sus detalles.',
    placement: 'right',
    page: '/dashboard',
  },
  {
    target: '[data-tour="nav-tareas"]',
    title: 'Vista de Tareas',
    description: 'Accede a la vista completa de tareas con filtros avanzados, búsqueda y organización por proyectos.',
    placement: 'right',
    page: '/dashboard',
  },
  {
    target: '[data-tour="nav-tablero"]',
    title: 'Tablero Kanban 📋',
    description: 'Visualiza y gestiona el flujo de trabajo con columnas: Pendiente, En Progreso, Hecho, Finalizado y Cancelado. Arrastra y suelta tareas entre columnas.',
    placement: 'right',
    page: '/dashboard',
  },
  {
    target: '[data-tour="nav-agenda"]',
    title: 'Agenda / Calendario 📅',
    description: 'Vista de calendario para planificar y visualizar tareas por fecha. Ve qué tareas vencen cada día y planifica tu semana.',
    placement: 'right',
    page: '/dashboard',
  },
  {
    target: '[data-tour="nav-grupos"]',
    title: 'Grupos de trabajo 👥',
    description: 'Crea y gestiona equipos. Invita miembros con códigos, asigna funciones internas y colabora en tareas compartidas.',
    placement: 'right',
    page: '/dashboard',
  },
  {
    target: '[data-tour="nav-historial"]',
    title: 'Historial 📜',
    description: 'Revisa el historial de tareas completadas, canceladas y restauradas. Filtra por fechas y proyectos.',
    placement: 'right',
    page: '/dashboard',
  },
  {
    target: '[data-tour="chat-btn"]',
    title: 'Chat de equipo 💬',
    description: 'Comunícate con tu equipo en tiempo real. Hay canales por área (General, Desarrollo, Marketing, Gerencia).',
    placement: 'bottom',
    page: '/dashboard',
  },
  {
    target: '[data-tour="user-menu"]',
    title: 'Tu perfil y configuración ⚙️',
    description: 'Accede a tu perfil, cambia de rol (Admin/Operador) con código de acceso, y cierra sesión. Los administradores tienen acceso completo y los operadores ven solo sus tareas asignadas.',
    placement: 'bottom',
    page: '/dashboard',
  },
];
